let selected=null;let selectedEl=null;const selectedDirKey='micros.files.selectedDir';let selectedDir=loadSelectedDir();let _editorScriptLoaded=false;let editorFile=null;const folders=document.getElementById('folders');function loadSelectedDir(){try{return sessionStorage.getItem(selectedDirKey)||'user_data';}catch(_){return'user_data';}}
function rememberDir(dir){selectedDir=dir||'user_data';try{sessionStorage.setItem(selectedDirKey,selectedDir);}catch(_){}}
let _msgTimer,_fadeTimer;function popUpMsg(msg,type='error',timeout=5000){let el=document.getElementById('root-message');if(!el){el=document.createElement('div');el.id='root-message';Object.assign(el.style,{position:'fixed',top:'8px',left:'50%',transform:'translateX(-50%)',color:'#fff',padding:'6px 12px',borderRadius:'4px',fontSize:'12px',zIndex:'99999',transition:'opacity 0.4s ease',opacity:'0'});document.body.appendChild(el);}
el.textContent=msg;el.style.background=type==='error'?'rgba(220,60,60,.9)':type==='success'?'rgba(45,145,75,.95)':'rgba(45,105,180,.95)';el.style.display='block';requestAnimationFrame(()=>el.style.opacity='1');clearTimeout(_msgTimer);clearTimeout(_fadeTimer);if(timeout){_msgTimer=setTimeout(()=>{el.style.opacity='0';_fadeTimer=setTimeout(()=>el.style.display='none',400);},timeout);}}
function clearSelection(){if(selectedEl)selectedEl.classList.remove('sel');fileActionBar.remove();selected=null;selectedEl=null;}
function itemRow(cls,name,meta){const d=document.createElement('div');const nameEl=document.createElement('span');const metaEl=document.createElement('span');d.className=cls;nameEl.className='item-name';metaEl.className='item-meta';nameEl.textContent=name;metaEl.textContent=meta;d.appendChild(nameEl);d.appendChild(metaEl);return d;}
const fileActions={open:openFile,edit:editor,delete:deleteFile};const fileActionBar=document.createElement('span');fileActionBar.className='file-actions';fileActionBar.innerHTML='<button type="button" data-action="open">📖 Open</button>'+'<button type="button" data-action="edit">📄 Edit</button>'+'<button type="button" class="danger" data-action="delete" title="Delete" aria-label="Delete">♻</button>';fileActionBar.onclick=e=>{e.stopPropagation();const action=e.target.dataset.action;if(action)fileActions[action]();};function selectFile(e){const row=e.currentTarget;e.stopPropagation();if(selectedEl===row)return clearSelection();clearSelection();row.classList.add('sel');selected=row.dataset.name;selectedEl=row;row.appendChild(fileActionBar);}
function fileRow(name,size){const d=itemRow('file-item',name,sizeText(size));d.dataset.name=name;d.onclick=selectFile;return d;}
function sizeText(bytes){const units='BKMG';let value=Number(bytes)||0,unit=0;while(value>=1024&&unit<units.length-1){value/=1024;unit+=1;}
const digits=unit>0&&value<10&&value%1?1:0;return`${value.toFixed(digits)}${units[unit]}`;}
function kbText(bytes){return`${Math.ceil(bytes / 1024)} KB`;}
function load(){console.info('load.loadDirs');loadDirs().then(()=>{console.info('load.loadFiles:',selectedDir);loadFiles();});console.info('load.loadDiskUsage');updateDiskUsage();}
function loadFiles(){const contentList=document.getElementById('list');contentList.classList.add('loading');fetch('/fs/list',{method:'POST',headers:{'Content-Type':'text/plain'},body:selectedDir||'/'}).then(r=>r.json()).then(files=>{contentList.innerHTML='';clearSelection();if(!Array.isArray(files)||files.length===0){const d=document.createElement('div');d.className='file-item placeholder';d.textContent='.empty';d.style.opacity='0.5';d.style.pointerEvents='none';contentList.appendChild(d);console.info("Files loaded (empty folder)");return;}
files.forEach(f=>{const name=f.path.split('/').pop();const d=fileRow(name,f.size);contentList.appendChild(d);});console.info("Files loaded");}).catch(err=>{console.error("load failed:",err);popUpMsg("Failed to load files: "+err.message);}).finally(()=>{contentList.classList.remove('loading');});}
function loadDirs(){return fetch('/fs/dirs').then(r=>r.json()).then(dirs=>{const container=document.getElementById('folder-path');container.innerHTML='';if(!Array.isArray(dirs)||!dirs.length)return;dirs.forEach(dir=>{const path=typeof dir==='string'?dir:dir[0];const access=typeof dir==='string'?'r':dir[1];const normalized=path.replace(/^\/+/,'');const d=itemRow('dir-item',normalized,access||'r');d.dataset.path=normalized;d.onclick=()=>{document.querySelectorAll('#folder-path .dir-item').forEach(x=>x.className='dir-item');d.className='dir-item sel';rememberDir(normalized);if(window.innerWidth<=768&&window.innerHeight>window.innerWidth)folders.classList.remove('open');console.info('dirChange.loadFiles:',selectedDir);loadFiles();};if(!selectedDir){rememberDir(normalized);d.className='dir-item sel';}
else if(normalized===selectedDir){d.className='dir-item sel';}
container.appendChild(d);console.info("Folders loaded");});if(!container.querySelector('.dir-item.sel')&&container.firstChild){rememberDir(container.firstChild.dataset.path);container.firstChild.classList.add('sel');}}).catch(err=>{console.error("dirs load failed:",err);popUpMsg("Failed to load folders: "+err.message);})}
async function uploadFile(fileToUpload){const f=fileToUpload||file.files[0];if(!f)return false;const chunkSize=1024;const totalChunks=Math.max(1,Math.ceil(f.size/chunkSize));const fd=new FormData();const targetPath=f.name.includes('/')||f.name[0]==='$'?f.name.replace(/^\/+/,''):`${selectedDir}/${f.name}`;for(let i=0;i<totalChunks;i++){const start=i*chunkSize;const end=Math.min(f.size,start+chunkSize);fd.append(`chunk_${i + 1}`,f.slice(start,end),targetPath);}
console.info("Uploading (multipart chunked):",targetPath);try{popUpMsg(`Uploading ${kbText(f.size)}…`,'info',0);const r=await fetch('/fs/files',{method:'POST',body:fd});if(!r.ok){const resp=(await r.text())||r.statusText;throw new Error(`${r.status} - ${resp}`);}
popUpMsg(`Uploaded ${kbText(f.size)}`,'success',1500);return true;}catch(err){console.error("uploadFile error:",err);popUpMsg("Upload failed: "+err.message);return false;}}
window.uploadFile=uploadFile;window.addEventListener('micros-editor-close',()=>{editorFile=null;});function openFile(){if(!selected)return;const resource=`/${selectedDir}/${selected}`;console.info('openFile:',resource);window.open(resource);}
function deleteFile(){if(!selected)return;if(!window.confirm(`Delete ${selected}?`))return;const toDelete=`/${selectedDir}/${selected}`;console.info("deleteFile:",toDelete);fetch('/fs/files',{method:'DELETE',body:toDelete}).then(async r=>{if(!r.ok){const resp=(await r.text())||r.statusText;throw new Error(`${r.status} - ${resp}`);}
return r;}).then(()=>{if(_editorScriptLoaded&&editorFile===toDelete){if(window.destroyEditor)window.destroyEditor();editorFile=null;console.info("deleteFile: editor destroyed");}}).then(load).catch(err=>{console.error("deleteFile failed:",err);popUpMsg("Delete failed: "+err.message);});}
function loadEditorScript(){if(_editorScriptLoaded)return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='../editor.js';s.onload=()=>{_editorScriptLoaded=true;resolve();};s.onerror=reject;document.head.appendChild(s);});}
async function editor(){const filename=selected??`LM_blinky.py`;const resource=`/${selectedDir}/${filename}`;console.info('editor:',resource);await loadEditorScript();let container=document.getElementById('editor');if(!container){container=document.createElement('div');container.id='editor';}
window.createEditor(container);window.openEditor(resource,{anchor:selectedEl,list:document.getElementById('list')});editorFile=resource;}
function newFile(){clearSelection();return editor();}
function updateDiskUsage(){fetch('/fs/usage').then(r=>r.json()).then(data=>{const usedMB=(data.used/(1024*1024)).toFixed(1);const freeMB=(data.free/(1024*1024)).toFixed(1);const total=data.used+data.free;const percent=total?(data.used/total)*100:0;document.getElementById('disktext').textContent=`Disk: ${usedMB} MB used / ${freeMB} MB free`;document.getElementById('diskused').style.width=`${percent.toFixed(1)}%`;console.info("DiskUsage: update");}).catch(err=>{console.error("disk usage failed:",err);popUpMsg("Disk usage unavailable: "+err.message);})}
document.addEventListener('click',(e)=>{if(e.target.closest('button'))return;if(_editorScriptLoaded&&editorFile)return;const list=document.getElementById('list');const editor=document.getElementById('editor');if(list&&!list.contains(e.target)&&(!editor||!editor.contains(e.target))){clearSelection();}});function closeFoldersOnOutsideClick(e){const toggle=document.getElementById('menuToggle');const isMobileFoldersMenu=window.innerWidth<=768&&window.innerHeight>window.innerWidth;if(!isMobileFoldersMenu||!folders.classList.contains('open'))return;if(folders.contains(e.target)||(toggle&&toggle.contains(e.target)))return;folders.classList.remove('open');}
document.addEventListener('pointerdown',closeFoldersOnOutsideClick);document.getElementById('menuToggle').onclick=()=>folders.classList.toggle('open');load();
