function moduleCommandSuggestions(response){const result=response&&Object.prototype.hasOwnProperty.call(response,'result')?response.result:response;let modules=Array.isArray(result)?result:[];if(!modules.length&&typeof result==='string'){try{modules=JSON.parse(result);}catch(_){const matches=result.match(/["'][A-Za-z_][A-Za-z0-9_]*["']/g)||[];modules=matches.map(moduleName=>moduleName.slice(1,-1));}}
return[...new Set((Array.isArray(modules)?modules:[]).map(moduleName=>typeof moduleName==='string'?moduleName.trim():'').filter(moduleName=>/^[A-Za-z_][A-Za-z0-9_]*$/.test(moduleName)))].flatMap(command=>{if(command==='task'){return['task list','task show <taskID>','task kill <taskID>'];}
return[`${command} help`];});}
function restWidget(container='restWidget',opts={}){const root=byId(container);if(!root){return null;}
const styled=(el,css)=>{el.style.cssText=css;return el;};const prefix=opts.prefix?`${opts.prefix}-`:'';const inputId=opts.inputId||`${prefix}restCmdInput`;const historyKey=opts.historyKey||'micros.rest.commands';let history=[];try{history=JSON.parse(sessionStorage.getItem(historyKey)||'[]').filter(x=>typeof x==='string');}catch(_){}
let suggestions=['modules'];const label=makeEl('label',{htmlFor:inputId,textContent:opts.label||'🚀 Enter micrOS command: '});const input=styled(makeEl('input',{type:'text',id:inputId,value:opts.value||''}),'background:transparent;max-width:none;min-width:0;padding-right:34px;position:relative;width:100%;z-index:1;');const ghost=styled(makeEl('span'),'box-sizing:border-box;color:rgba(255,255,255,.35);font:14px/1.4 Verdana,sans-serif;inset:2px;overflow:hidden;padding:6px 34px 6px 12px;pointer-events:none;position:absolute;white-space:pre;');const accept=styled(makeEl('button',{type:'button',textContent:'↦',title:'Accept suggestion'}),'bottom:2px;display:none;min-height:0;padding:0 8px;position:absolute;right:2px;top:2px;z-index:3;');const send=makeEl('button',{type:'submit',textContent:opts.button||'Send'});const inputWrap=styled(makeEl('span',{},[input,ghost,accept]),'flex:1;max-width:350px;min-width:200px;position:relative;');const form=makeEl('form',{},[inputWrap,send]);const url=makeEl('p',{id:opts.urlId||`${prefix}restConsoleUrl`});const responseBox=makeEl('pre',{id:opts.responseId||`${prefix}restConsoleResponse`});const time=makeEl('p',{id:opts.timeId||`${prefix}restConsoleTime`});const updateHint=()=>{const commands=[...new Set([...history,...suggestions])];ghost.textContent=input.value&&commands.find(x=>x.startsWith(input.value)&&x!==input.value)||'';accept.style.display=ghost.textContent?'':'none';};const acceptHint=()=>{if(!ghost.textContent){return;}
const suffix=ghost.textContent.slice(input.value.length);const word=suffix.match(/^\s*\S+\s*/);input.value+=word?word[0]:suffix;input.setSelectionRange(input.value.length,input.value.length);updateHint();input.focus();};input.oninput=updateHint;const submitCommand=()=>{const cmd=input.value.trim();if(cmd){history=[cmd,...history.filter(x=>x!==cmd)].slice(0,opts.historyLimit||20);try{sessionStorage.setItem(historyKey,JSON.stringify(history));}catch(_){}}
updateHint();restAPICore(cmd,opts.timeout||5000).then(({response,delta,query})=>restConsole(query,response,delta,{url,response:responseBox,time})).catch(error=>restConsole('restAPI error',{error:error.message},0,{url,response:responseBox,time}));return false;};input.onkeydown=e=>{if(e.key==='Tab'&&ghost.textContent){e.preventDefault();acceptHint();}else if(e.key==='Enter'){e.preventDefault();submitCommand();}};accept.onclick=acceptHint;form.onsubmit=submitCommand;root.textContent='';root.append(makeEl('h3',{},[label]),form,url,responseBox,time);if(REST_CONSOLE_CACHE){restConsole(...REST_CONSOLE_CACHE,{url,response:responseBox,time});}
updateHint();restAPICore('modules',opts.modulesTimeout||3000).then(({response})=>{const commands=moduleCommandSuggestions(response);if(!commands.length){return;}
suggestions=[...new Set(['modules',...commands])];updateHint();}).catch(error=>console.error('Error loading command suggestions:',error));return{root,input,form,url,response:responseBox,time};}
function initApiConsole(id='apiConsole',widget='restWidget'){const box=byId(id);if(!box){return;}
apiConsoleStyle();const render=()=>{if(box.open&&!box.dataset.r){restWidget(widget);box.dataset.r=1;}};box.ontoggle=render;render();}
const endpointIconMap={dashboard:'🎮',fs:'📁',config:'⚙️'};function endpointLabel(label,entry){const icon=endpointIconMap[String(entry).replace(/^\/+|\/+$/g,'')];return icon?`${icon} ${label}`:label;}
function renderEndpointGroups(endpoints){const container=byId('endpointGroups');if(!container){return;}
container.textContent='';if(!Array.isArray(endpoints)||!endpoints.length){const loadApps=makeEl('button',{className:'endpoint-main',textContent:'🚀 Load Web Apps',onclick:()=>{container.textContent='';restAPI('web/load',false).finally(()=>location.reload());}});container.appendChild(makeEl('div',{className:'endpoint-group'},[loadApps]));return;}
const groups={};const button=(label,entry,className='')=>makeEl('button',{className,textContent:label,onclick:()=>window.open(`/${entry}`,'_blank')});endpoints.forEach(endpoint=>{const target=String(endpoint||'').replace(/^\/+/,'');const[main,...subParts]=target.replace(/\/+$/,'').split('/');if(!main){return;}
const group=groups[main]||(groups[main]={root:null,children:[]});if(subParts.length){group.children.push({entry:target,label:subParts.join('/')});}else if(!group.root||target.endsWith('/')){group.root=target;}});Object.keys(groups).sort().forEach(main=>{const group=groups[main];const mainAction=group.root?button(endpointLabel(main,group.root),group.root,'endpoint-main'):makeEl('span',{className:'endpoint-main endpoint-main-label',textContent:endpointLabel(main,main)});const actions=makeEl('div',{className:'endpoint-group-actions'});group.children.sort((a,b)=>a.entry.localeCompare(b.entry)).forEach(({entry,label})=>actions.appendChild(button(endpointLabel(label,entry),entry)));container.appendChild(makeEl('div',{className:'endpoint-group'},group.children.length?[mainAction,actions]:[mainAction]));});}
