global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'micros_gw_cabinet'
    metrics_path: /metrics/Cabinet/dht22+measure
    scheme: http
    static_configs:
      - targets: ['10.0.1.61:5000']

  - job_name: 'micros_gw_tinydevboard'
    metrics_path: /metrics/TerraceSensor/dht22+measure
    scheme: http
    static_configs:
      - targets: ['10.0.1.61:5000']


