global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'micros_gw_cabinet'
    metrics_path: /metrics/Cabinet/dht22+measure
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5005']

  - job_name: 'micros_gw_terracesensor'
    metrics_path: /metrics/TerraceSensor/dht22+measure
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5005']

  - job_name: 'micros_gw_terracesensorr'
    metrics_path: /metrics/TerraceSensor/light_sensor+intensity
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5005']

  - job_name: 'micros_gw_tinydevboard'
    metrics_path: /metrics/TinyDevBoard/system+top
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5005']

