global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'micros_gw_cabinet'
    metrics_path: /metrics/Cabinet/dht22+measure
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5000']

  - job_name: 'micros_gw_terracesensor'
    metrics_path: /metrics/TerraceSensor/dht22+measure
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5000']

  - job_name: 'micros_gw_tinydevboard'
    metrics_path: /metrics/TinyDevBoard/system+info
    scheme: http
    static_configs:
      - targets: ['micros-gateway:5000']


