#!/usr/bin/env python3
"""
Build a MicroPython firmware image with the micrOS core frozen into it.

Only Python files directly inside ``micrOS/source`` are frozen. Subdirectories
such as ``modules``, ``web`` and ``config`` are deliberately excluded.

The direct source set includes ``main.py``. MicroPython's ESP32 startup checks
for a frozen ``main.py`` before checking the writable filesystem, so micrOS
starts directly from the firmware image.
"""

import argparse
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
from time import monotonic


REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
MICROS_SOURCE = REPOSITORY_ROOT / "micrOS" / "source"
DEFAULT_OUTPUT_DIR = REPOSITORY_ROOT / "micrOS" / "micropython"
WORKSPACE_BUILD_DIR = REPOSITORY_ROOT / "toolkit" / "workspace" / "build"
DEFAULT_BUILD_DIR = WORKSPACE_BUILD_DIR / "micrOSImageBuilder"
DEFAULT_MICROPYTHON_DIR = WORKSPACE_BUILD_DIR / "micropython"
DEFAULT_ESP_IDF_DIR = WORKSPACE_BUILD_DIR / "esp-idf"
DEFAULT_IDF_TOOLS_DIR = WORKSPACE_BUILD_DIR / "esp-idf-tools"
MICROPYTHON_REPOSITORY = "https://github.com/micropython/micropython.git"
ESP_IDF_REPOSITORY = "https://github.com/espressif/esp-idf.git"

# Keep releases pinned so that firmware builds remain reproducible.
MICROPYTHON_STABLE_VERSION = "v1.28.0"
ESP_IDF_VERSION = "v5.5.1"

# Add future targets here after their MicroPython board build has been tested.
SUPPORTED_DEVICES = {
    "esp32c6": {
        "description": "Generic ESP32-C6 (4 MiB flash or larger)",
        "micropython_board": "ESP32_GENERIC_C6",
        "idf_target": "esp32c6",
        "status": "supported",
    },
}


class BuildError(RuntimeError):
    """Raised when the image cannot be built safely."""


def log(level, message):
    """Emit a consistent, grep-friendly build message."""
    print("[micrOS-image][{}] {}".format(level.upper(), message), flush=True)


def log_step(number, total, message):
    log("STEP {}/{}".format(number, total), message)


def micros_version(source_dir=MICROS_SOURCE):
    """Read the micrOS release version without importing embedded modules."""
    shell_path = Path(source_dir) / "Shell.py"
    try:
        shell_source = shell_path.read_text(encoding="utf-8")
    except OSError as exc:
        raise BuildError("Cannot read micrOS version from: {}".format(shell_path)) from exc

    match = re.search(
        r"^\s*MICROS_VERSION\s*=\s*['\"]([^'\"]+)['\"]",
        shell_source,
        flags=re.MULTILINE,
    )
    if not match:
        raise BuildError("MICROS_VERSION was not found in: {}".format(shell_path))
    return match.group(1)


def core_source_files(source_dir=MICROS_SOURCE):
    """Return only direct ``source/*.py`` files, in deterministic order."""
    source_dir = Path(source_dir)
    if not source_dir.is_dir():
        raise BuildError("micrOS source directory does not exist: {}".format(source_dir))

    files = sorted(
        path.name
        for path in source_dir.iterdir()
        if path.is_file() and path.suffix == ".py"
    )
    if not files:
        raise BuildError("No micrOS core Python files found in: {}".format(source_dir))
    if "main.py" not in files:
        raise BuildError("micrOS/source/main.py is required for firmware startup")
    return files


def manifest_text(source_dir=MICROS_SOURCE):
    """Create the MicroPython frozen-module manifest."""
    source_dir = Path(source_dir).resolve()
    files = core_source_files(source_dir)
    file_lines = "\n".join('        "{}",'.format(name) for name in files)
    return """# Generated by toolkit/micrOSImageBuilder.py; do not edit.
# Minimal ESP32 runtime support. Deliberately do not freeze the port's
# espnow.py or micropython-lib's urequests.py because micrOS owns modules with
# those names (Espnow.py and urequests.py).
module("_boot.py", base_path="$(PORT_DIR)/modules")
module("apa106.py", base_path="$(PORT_DIR)/modules")
module("flashbdev.py", base_path="$(PORT_DIR)/modules")
module("inisetup.py", base_path="$(PORT_DIR)/modules")
module("machine.py", base_path="$(PORT_DIR)/modules")

include("$(MPY_DIR)/extmod/asyncio")
require("mip")
require("ntptime")
require("requests")
require("ssl")
require("webrepl")

# Freeze only direct micrOS/source/*.py files. No child directory is included.
freeze(
    {source_dir!r},
    (
{file_lines}
    ),
    opt=3,
)
""".format(source_dir=str(source_dir), file_lines=file_lines)


def write_manifest(output_dir, source_dir=MICROS_SOURCE):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = output_dir / "micrOS-manifest.py"
    manifest_path.write_text(manifest_text(source_dir), encoding="utf-8")
    return manifest_path


def run(command, cwd, env=None):
    printable = " ".join(str(part) for part in command)
    log("RUN", "{} (cwd: {})".format(printable, cwd))
    started = monotonic()
    try:
        subprocess.run(
            [str(part) for part in command],
            cwd=str(cwd),
            env=env,
            check=True,
        )
    except FileNotFoundError as exc:
        raise BuildError("Required command is unavailable: {}".format(command[0])) from exc
    except subprocess.CalledProcessError as exc:
        raise BuildError("Command failed with exit code {}: {}".format(exc.returncode, printable)) from exc
    log("OK", "Command completed in {:.1f}s".format(monotonic() - started))


def ensure_micropython_checkout(micropython_dir):
    """Clone the pinned MicroPython release when the managed checkout is absent."""
    micropython_dir = Path(micropython_dir).expanduser().resolve()
    if micropython_dir.exists():
        log("INFO", "Using MicroPython checkout: {}".format(micropython_dir))
        return micropython_dir

    micropython_dir.parent.mkdir(parents=True, exist_ok=True)
    log("INFO", "MicroPython checkout missing; cloning {}".format(MICROPYTHON_STABLE_VERSION))
    run(
        [
            "git",
            "clone",
            "--branch",
            MICROPYTHON_STABLE_VERSION,
            "--depth",
            "1",
            MICROPYTHON_REPOSITORY,
            str(micropython_dir),
        ],
        cwd=micropython_dir.parent,
    )
    return micropython_dir


def ensure_esp_idf_checkout(esp_idf_dir):
    """Clone the ESP-IDF release required by the pinned MicroPython version."""
    esp_idf_dir = Path(esp_idf_dir).expanduser().resolve()
    if esp_idf_dir.exists():
        if not (esp_idf_dir / "export.sh").is_file():
            raise BuildError("Not an ESP-IDF source checkout: {}".format(esp_idf_dir))
        log("INFO", "Using ESP-IDF checkout: {}".format(esp_idf_dir))
        return esp_idf_dir

    esp_idf_dir.parent.mkdir(parents=True, exist_ok=True)
    log("INFO", "ESP-IDF checkout missing; cloning {}".format(ESP_IDF_VERSION))
    run(
        [
            "git",
            "clone",
            "--branch",
            ESP_IDF_VERSION,
            "--depth",
            "1",
            "--recursive",
            "--shallow-submodules",
            ESP_IDF_REPOSITORY,
            str(esp_idf_dir),
        ],
        cwd=esp_idf_dir.parent,
    )
    return esp_idf_dir


def idf_environment(esp_idf_dir, idf_target, tools_dir=DEFAULT_IDF_TOOLS_DIR):
    """Install ESP-IDF tools when needed and return its exported environment."""
    esp_idf_dir = Path(esp_idf_dir).expanduser().resolve()
    tools_dir = Path(tools_dir).expanduser().resolve()
    tools_dir.mkdir(parents=True, exist_ok=True)

    env = os.environ.copy()
    env["IDF_TOOLS_PATH"] = str(tools_dir)
    install_marker = tools_dir / ".micros-{}-{}-installed".format(
        ESP_IDF_VERSION, idf_target
    )
    if not install_marker.is_file():
        log("INFO", "Installing ESP-IDF tools for target {}".format(idf_target))
        run(["./install.sh", idf_target], cwd=esp_idf_dir, env=env)
        install_marker.touch()
    else:
        log("INFO", "ESP-IDF tools already installed for target {}".format(idf_target))

    log("INFO", "Loading ESP-IDF environment")
    try:
        result = subprocess.run(
            [
                "bash",
                "-c",
                'source "$1/export.sh" >/dev/null && env -0',
                "bash",
                str(esp_idf_dir),
            ],
            env=env,
            check=True,
            capture_output=True,
        )
    except FileNotFoundError as exc:
        raise BuildError("bash is required to load the ESP-IDF environment") from exc
    except subprocess.CalledProcessError as exc:
        raise BuildError("Failed to load ESP-IDF environment") from exc

    exported_env = {}
    for item in result.stdout.split(b"\0"):
        if b"=" in item:
            key, value = item.split(b"=", 1)
            exported_env[os.fsdecode(key)] = os.fsdecode(value)

    missing_build_tools = [
        tool
        for tool in ("cmake", "ninja")
        if shutil.which(tool, path=exported_env.get("PATH")) is None
    ]
    if missing_build_tools:
        python_env = exported_env.get("IDF_PYTHON_ENV_PATH")
        if not python_env:
            raise BuildError("ESP-IDF did not export IDF_PYTHON_ENV_PATH")
        python_executable = Path(python_env) / "bin" / "python"
        log(
            "INFO",
            "Installing missing build utilities: {}".format(
                ", ".join(missing_build_tools)
            ),
        )
        run(
            [python_executable, "-m", "pip", "install"] + missing_build_tools,
            cwd=esp_idf_dir,
            env=exported_env,
        )

    for tool in ("cmake", "ninja"):
        tool_path = shutil.which(tool, path=exported_env.get("PATH"))
        if tool_path is None:
            raise BuildError("{} is unavailable after ESP-IDF setup".format(tool))
        log("OK", "{}: {}".format(tool, tool_path))
    return exported_env


def validate_git_version(checkout_dir, expected_version, component, allow_version_mismatch=False):
    """Require a reproducible, exact release checkout."""
    if not allow_version_mismatch:
        try:
            result = subprocess.run(
                ["git", "describe", "--tags", "--exact-match"],
                cwd=str(checkout_dir),
                check=True,
                capture_output=True,
                text=True,
            )
        except (FileNotFoundError, subprocess.CalledProcessError) as exc:
            raise BuildError(
                "{} must be checked out exactly at {}. "
                "Use --allow-version-mismatch only for intentional testing."
                .format(component, expected_version)
            ) from exc
        actual_version = result.stdout.strip()
        if actual_version != expected_version:
            raise BuildError(
                "Expected {} {}, found {}. "
                "Checkout the stable tag or use --allow-version-mismatch."
                .format(component, expected_version, actual_version or "unknown")
            )
        log("OK", "{} version: {}".format(component, actual_version))


def validate_micropython_checkout(micropython_dir, allow_version_mismatch=False):
    micropython_dir = Path(micropython_dir).expanduser().resolve()
    esp32_port = micropython_dir / "ports" / "esp32"
    if not (micropython_dir / "mpy-cross").is_dir() or not esp32_port.is_dir():
        raise BuildError(
            "Not a MicroPython source checkout: {}".format(micropython_dir)
        )
    validate_git_version(
        micropython_dir,
        MICROPYTHON_STABLE_VERSION,
        "MicroPython",
        allow_version_mismatch,
    )
    return micropython_dir


def build_image(
    device_name,
    micropython_dir,
    esp_idf_dir,
    output_dir,
    build_dir=DEFAULT_BUILD_DIR,
    allow_version_mismatch=False,
):
    device = SUPPORTED_DEVICES[device_name]
    started = monotonic()
    log("BUILD", "micrOS firmware image build started")
    log("INFO", "Target: {} ({})".format(device_name, device["micropython_board"]))
    log("INFO", "Output directory: {}".format(Path(output_dir).expanduser().resolve()))

    log_step(1, 7, "Validate source selection and generate frozen manifest")
    source_files = core_source_files()
    log("INFO", "Freezing {} direct source/*.py files:".format(len(source_files)))
    for source_file in source_files:
        log("SOURCE", source_file)

    micropython_dir = ensure_micropython_checkout(micropython_dir)
    micropython_dir = validate_micropython_checkout(
        micropython_dir,
        allow_version_mismatch=allow_version_mismatch,
    )
    output_dir = Path(output_dir).expanduser().resolve()
    build_dir = Path(build_dir).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = write_manifest(build_dir)
    log("OK", "Frozen manifest: {}".format(manifest_path))

    log_step(2, 7, "Prepare pinned ESP-IDF and toolchain")
    esp_idf_dir = ensure_esp_idf_checkout(esp_idf_dir)
    validate_git_version(
        esp_idf_dir,
        ESP_IDF_VERSION,
        "ESP-IDF",
        allow_version_mismatch,
    )
    env = idf_environment(esp_idf_dir, device["idf_target"])
    board = device["micropython_board"]
    esp32_port = micropython_dir / "ports" / "esp32"

    log_step(3, 7, "Build MicroPython cross-compiler")
    run(["make", "-C", "mpy-cross"], cwd=micropython_dir, env=env)
    log_step(4, 7, "Clean target build to prevent stale frozen modules")
    run(["make", "clean", "BOARD={}".format(board)], cwd=esp32_port, env=env)
    log_step(5, 7, "Prepare MicroPython ESP32 submodules")
    run(["make", "submodules", "BOARD={}".format(board)], cwd=esp32_port, env=env)
    log_step(6, 7, "Build ESP32-C6 firmware with frozen micrOS core")
    run(
        [
            "make",
            "BOARD={}".format(board),
            "FROZEN_MANIFEST={}".format(manifest_path),
        ],
        cwd=esp32_port,
        env=env,
    )

    firmware_source = esp32_port / "build-{}".format(board) / "firmware.bin"
    if not firmware_source.is_file():
        raise BuildError("Build completed without producing: {}".format(firmware_source))

    log_step(7, 7, "Publish versioned firmware image")
    micropython_version = MICROPYTHON_STABLE_VERSION.lstrip("v")
    firmware_output = output_dir / "micrOS-{}-{}-{}.bin".format(
        device_name,
        micropython_version,
        micros_version(),
    )
    shutil.copy2(str(firmware_source), str(firmware_output))

    log("SUCCESS", "Firmware: {}".format(firmware_output))
    log("SUCCESS", "Completed in {:.1f}s".format(monotonic() - started))
    log("BOOT", "Frozen main.py will be executed automatically by MicroPython")
    return firmware_output


def print_supported_devices():
    log("INFO", "Supported devices:")
    for name, device in sorted(SUPPORTED_DEVICES.items()):
        print(
            "  {name:<12} {board:<24} {status:<10} {description}".format(
                name=name,
                board=device["micropython_board"],
                status=device["status"],
                description=device["description"],
            )
        )


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description=(
            "Build stable MicroPython with direct micrOS/source/*.py core files "
            "frozen into the firmware."
        )
    )
    parser.add_argument(
        "--device",
        choices=sorted(SUPPORTED_DEVICES),
        default="esp32c6",
        help="target device (default: esp32c6)",
    )
    parser.add_argument(
        "--micropython-dir",
        default=str(DEFAULT_MICROPYTHON_DIR),
        help=(
            "MicroPython checkout; cloned automatically when absent "
            "(default: toolkit/workspace/build/micropython)"
        ),
    )
    parser.add_argument(
        "--esp-idf-dir",
        default=str(DEFAULT_ESP_IDF_DIR),
        help=(
            "ESP-IDF checkout; cloned and configured automatically when absent "
            "(default: toolkit/workspace/build/esp-idf)"
        ),
    )
    parser.add_argument(
        "--output-dir",
        default=str(DEFAULT_OUTPUT_DIR),
        help="firmware destination (default: micrOS/micropython)",
    )
    parser.add_argument(
        "--build-dir",
        default=str(DEFAULT_BUILD_DIR),
        help="temporary manifest and bootstrap destination",
    )
    parser.add_argument(
        "--manifest-only",
        action="store_true",
        help="generate the manifest without invoking the compiler",
    )
    parser.add_argument(
        "--list-devices",
        action="store_true",
        help="show supported device identifiers and exit",
    )
    parser.add_argument(
        "--allow-version-mismatch",
        action="store_true",
        help="allow an intentional build from a tag other than the pinned stable release",
    )
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    if args.list_devices:
        print_supported_devices()
        return 0

    if args.manifest_only:
        manifest_path = write_manifest(args.build_dir)
        source_files = core_source_files()
        log("OK", "Manifest: {}".format(manifest_path))
        log("INFO", "Frozen core files: {}".format(len(source_files)))
        for source_file in source_files:
            log("SOURCE", source_file)
        return 0

    build_image(
        args.device,
        args.micropython_dir,
        args.esp_idf_dir,
        args.output_dir,
        build_dir=args.build_dir,
        allow_version_mismatch=args.allow_version_mismatch,
    )
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BuildError as error:
        print("[micrOS-image][ERROR] {}".format(error), file=sys.stderr, flush=True)
        sys.exit(1)
