{
 "title": "micrOS sysMetrics",
 "description": "micrOS system top metrics",
 "tags": [
  "metrics",
  "system",
  "micrOS"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Device metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TinyDevBoard metrics",
   "type": "stat",
   "description": "system top command output\n- basic system monitoring with CPU, Memory, FS metrics",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_TinyDevBoard__system_top_CPU",
     "legendFormat": "CPU"
    },
    {
     "expr": "micrOS_TinyDevBoard__system_top_Mem",
     "legendFormat": "RAM"
    },
    {
     "expr": "micrOS_TinyDevBoard__system_top_FS",
     "legendFormat": "DISK"
    }
   ]
  },
  {
   "title": "Cabinet metrics",
   "type": "stat",
   "description": "system top command output\n- basic system monitoring with CPU, Memory, FS metrics",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "micrOS_Cabinet__system_top_CPU", "legendFormat": "CPU" },
    { "expr": "micrOS_Cabinet__system_top_Mem", "legendFormat": "RAM" },
    { "expr": "micrOS_Cabinet__system_top_FS", "legendFormat": "DISK" }
   ]
  },
  {
   "title": "LivingKitchen metrics",
   "type": "stat",
   "description": "system top command output\n- basic system monitoring with CPU, Memory, FS metrics",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_LivingKitchen__system_top_CPU",
     "legendFormat": "CPU"
    },
    {
     "expr": "micrOS_LivingKitchen__system_top_Mem",
     "legendFormat": "RAM"
    },
    {
     "expr": "micrOS_LivingKitchen__system_top_FS",
     "legendFormat": "DISK"
    }
   ]
  },
  {
   "title": "CamPro metrics",
   "type": "stat",
   "description": "system top command output\n- basic system monitoring with CPU, Memory, FS metrics",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "micrOS_CamPro__system_top_CPU", "legendFormat": "CPU" },
    { "expr": "micrOS_CamPro__system_top_Mem", "legendFormat": "RAM" },
    { "expr": "micrOS_CamPro__system_top_FS", "legendFormat": "DISK" }
   ]
  }
 ]
}