{
 "title": "TerraceSensor",
 "tags": [
  "Air",
  "Humidity",
  "Temperature",
  "Light"
 ],
 "time": { "from": "now-30h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container Services",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "\n<div>\nPortainer:\n<a href=\"http://gateway.local:9000\" target=\"_blank\">\n    <img src=\"https://img.shields.io/badge/Portainer-blue\" alt=\"micrOS_Gateway\">\n</a>\n\nDatabase and scraper: \n<a href=\"http://gateway.local:9090\" target=\"_blank\">\n    <img src=\"https://img.shields.io/badge/Prometheus-gray\" alt=\"   DockerHub\">\n</a>\n\n</div>\n\nmicrOS REST API:\n<a href=\"http://gateway.local:5000\" target=\"_blank\">\n    <img src=\"https://img.shields.io/badge/Gateway-purple\" alt=\"micrOS_Gateway\">\n</a>"
   }
  },
  { "title": "Light (TEMP6000)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Terrace Light",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "micrOS_TerraceSensor__light_sensor_intensity_light"
    }
   ]
  },
  {
   "title": "Terrace Light",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_TerraceSensor__light_sensor_intensity_light"
    }
   ]
  },
  { "title": "DHT22", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Terrace Air",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "micrOS_TerraceSensor__dht22_measure_tempC",
     "legendFormat": "temp [C]"
    },
    {
     "expr": "micrOS_TerraceSensor__dht22_measure_hum",
     "legendFormat": "hum [%]"
    }
   ]
  },
  {
   "title": "Terrace Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_TerraceSensor__dht22_measure_tempC"
    }
   ]
  },
  {
   "title": "Terrace Hum",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_TerraceSensor__dht22_measure_hum"
    }
   ]
  },
  {
   "title": "Livingroom Air",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "micrOS_Cabinet__dht22_measure_tempC",
     "legendFormat": "temp [C]"
    },
    {
     "expr": "micrOS_Cabinet__dht22_measure_hum",
     "legendFormat": "hum [%]"
    }
   ]
  },
  {
   "title": "Livingroom Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_Cabinet__dht22_measure_tempC"
    }
   ]
  },
  {
   "title": "Livingroom Hum",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "micrOS_Cabinet__dht22_measure_hum"
    }
   ]
  }
 ]
}